var searchData=
[
  ['uniformgrid_372',['UniformGrid',['../classUniformGrid.html#aafb52ed51365d9ca9d43c448d88fb0d2',1,'UniformGrid']]],
  ['updateagar_373',['UpdateAgar',['../Nutrients_8cpp.html#a7473241e51e8c800dc6caaa7c1a6659d',1,'UpdateAgar(Array3D&lt; LocalAga &gt; **Aga, Array3D&lt; LocalAga &gt; **prevAga, Array2D&lt; LocalAga &gt; **Wal, IntCoord position, int level):&#160;Nutrients.cpp'],['../Nutrients_8h.html#a7473241e51e8c800dc6caaa7c1a6659d',1,'UpdateAgar(Array3D&lt; LocalAga &gt; **Aga, Array3D&lt; LocalAga &gt; **prevAga, Array2D&lt; LocalAga &gt; **Wal, IntCoord position, int level):&#160;Nutrients.cpp']]],
  ['updateenvarray_374',['UpdateEnvArray',['../Nutrients_8cpp.html#aacb945c68f6ec009e33618fd1c901e29',1,'UpdateEnvArray(Array3D&lt; LocalEnv &gt; *CurrentColony, Array3D&lt; LocalEnv &gt; *PreviousColony, Array3D&lt; LocalAga &gt; **CurrentAgar, Array3D&lt; LocalAga &gt; **PreviousAgar, Array2D&lt; LocalAga &gt; **CurrentWall, Array2D&lt; LocalAga &gt; **PreviousWall, Array3D&lt; double &gt; &amp;DensityShiftP, Array3D&lt; double &gt; &amp;Density1ShiftP, Array3D&lt; double &gt; &amp;Density2ShiftP, Array2D&lt; double &gt; &amp;WallDensityShiftP, Array2D&lt; double &gt; &amp;WallDensity1ShiftP, Array2D&lt; double &gt; &amp;WallDensity2ShiftP, int minX, int maxX, int minY, int maxY, int maxH, Array2D&lt; double &gt; &amp;Height, Array3D&lt; double &gt; &amp;insideColonyDen):&#160;Nutrients.cpp'],['../Nutrients_8h.html#aacb945c68f6ec009e33618fd1c901e29',1,'UpdateEnvArray(Array3D&lt; LocalEnv &gt; *CurrentColony, Array3D&lt; LocalEnv &gt; *PreviousColony, Array3D&lt; LocalAga &gt; **CurrentAgar, Array3D&lt; LocalAga &gt; **PreviousAgar, Array2D&lt; LocalAga &gt; **CurrentWall, Array2D&lt; LocalAga &gt; **PreviousWall, Array3D&lt; double &gt; &amp;DensityShiftP, Array3D&lt; double &gt; &amp;Density1ShiftP, Array3D&lt; double &gt; &amp;Density2ShiftP, Array2D&lt; double &gt; &amp;WallDensityShiftP, Array2D&lt; double &gt; &amp;WallDensity1ShiftP, Array2D&lt; double &gt; &amp;WallDensity2ShiftP, int minX, int maxX, int minY, int maxY, int maxH, Array2D&lt; double &gt; &amp;Height, Array3D&lt; double &gt; &amp;insideColonyDen):&#160;Nutrients.cpp']]],
  ['updateenvironment_375',['UpdateEnvironment',['../Nutrients_8cpp.html#adb1b1a97aaa79d54d2f0c3b6b1952c82',1,'UpdateEnvironment(Array3D&lt; LocalEnv &gt; *Env, Array3D&lt; LocalEnv &gt; *prevEnv, Array2D&lt; LocalAga &gt; *prevWal, Array3D&lt; double &gt; &amp;DensityShiftP, Array3D&lt; double &gt; &amp;Density1ShiftP, Array3D&lt; double &gt; &amp;Density2ShiftP, Array2D&lt; double &gt; &amp;WallDensityShiftP, IntCoord position, Array3D&lt; double &gt; &amp;insideColonyDen):&#160;Nutrients.cpp'],['../Nutrients_8h.html#adb1b1a97aaa79d54d2f0c3b6b1952c82',1,'UpdateEnvironment(Array3D&lt; LocalEnv &gt; *Env, Array3D&lt; LocalEnv &gt; *prevEnv, Array2D&lt; LocalAga &gt; *prevWal, Array3D&lt; double &gt; &amp;DensityShiftP, Array3D&lt; double &gt; &amp;Density1ShiftP, Array3D&lt; double &gt; &amp;Density2ShiftP, Array2D&lt; double &gt; &amp;WallDensityShiftP, IntCoord position, Array3D&lt; double &gt; &amp;insideColonyDen):&#160;Nutrients.cpp']]],
  ['updatepositions_376',['UpdatePositions',['../Integrate_8cpp.html#aa22f0bd039da9eb29db7e08f2fe14c74',1,'UpdatePositions(double dt, const DoubleCoord &amp;F, DoubleCoord &amp;T, const Cell &amp;old_cell, Cell &amp;new_cell):&#160;Integrate.cpp'],['../Integrate_8h.html#aa22f0bd039da9eb29db7e08f2fe14c74',1,'UpdatePositions(double dt, const DoubleCoord &amp;F, DoubleCoord &amp;T, const Cell &amp;old_cell, Cell &amp;new_cell):&#160;Integrate.cpp']]],
  ['updatevelocities_377',['UpdateVelocities',['../Integrate_8cpp.html#ad43ededb50f03635818fe6190bf8a337',1,'UpdateVelocities(double dt, const DoubleCoord &amp;F, DoubleCoord &amp;T, const Cell &amp;old_cell, Cell &amp;new_cell):&#160;Integrate.cpp'],['../Integrate_8h.html#ad43ededb50f03635818fe6190bf8a337',1,'UpdateVelocities(double dt, const DoubleCoord &amp;F, DoubleCoord &amp;T, const Cell &amp;old_cell, Cell &amp;new_cell):&#160;Integrate.cpp']]],
  ['updatewall_378',['UpdateWall',['../Nutrients_8cpp.html#aba502c7f13da56519dd6b9cd8711dfb1',1,'UpdateWall(Array3D&lt; LocalEnv &gt; *Env, Array3D&lt; LocalAga &gt; **prevAga, Array2D&lt; LocalAga &gt; **Wal, Array2D&lt; LocalAga &gt; **prevWal, Array2D&lt; double &gt; &amp;WallDensityShiftP, Array2D&lt; double &gt; &amp;WallDensity1ShiftP, Array2D&lt; double &gt; &amp;WallDensity2ShiftP, IntCoord2D position, int level, Array2D&lt; double &gt; &amp;Height, Array3D&lt; double &gt; &amp;insideColonyDen):&#160;Nutrients.cpp'],['../Nutrients_8h.html#aba502c7f13da56519dd6b9cd8711dfb1',1,'UpdateWall(Array3D&lt; LocalEnv &gt; *Env, Array3D&lt; LocalAga &gt; **prevAga, Array2D&lt; LocalAga &gt; **Wal, Array2D&lt; LocalAga &gt; **prevWal, Array2D&lt; double &gt; &amp;WallDensityShiftP, Array2D&lt; double &gt; &amp;WallDensity1ShiftP, Array2D&lt; double &gt; &amp;WallDensity2ShiftP, IntCoord2D position, int level, Array2D&lt; double &gt; &amp;Height, Array3D&lt; double &gt; &amp;insideColonyDen):&#160;Nutrients.cpp']]]
];
